version: '3'

services:
  db:
      networks:
        - djangonetwork
      image: postgres:13.1
      volumes:
          - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=django-gatsby
      ports:
      - "5432:5432"

  api:
    restart: unless-stopped
    env_file:
      - development.env
    build: 
      context: ./backend
    command: python manage.py migrate --noinput
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge
volumes:
  postgres_data: